data_collection:
    start_date: 2008-01-01T00:00:00Z
    end_date: 2022-10-31T00:00:00Z
    query: "Alt-Right OR 'alternative right' OR altright OR #altright -is:retweet -is:mention lang:en"
    fields:
        tweet_fields: ["id", "created_at", "geo", "public_metrics", "text", "author_id", "possibly_sensitive", "lang"]
        user_fields: ["id", "username", "public_metrics", "description", "location", "created_at", "verified"]
