name: 3.10.8
channels:
  - conda-forge
dependencies:
  - python=3.10.8
  - tweepy=4.12.0
  - tqdm=4.64.1
  - pyyaml=6.0
  - pandas=1.5.1
  - matplotlib=3.5.3
  - scikit-learn=1.1.3
  - tqdm=4.64.1 
  - nltk=3.7 
  - jupyterlab=3.4.4


